spring.datasource.url=jdbc:h2:mem:arq_software
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Evita conflito local quando outra aplicação estiver usando 8080
server.port=8081

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

spring.sql.init.mode=always

#aws.sqs.queue.saida-estoque=SQS-SAIDA-ESTOQUE.fifo
#aws.sqs.queue.entrada-estoque=SQS-ENTRADA-ESTOQUE.fifo

# Configuracao local do Spring Cloud AWS 2.x
cloud.aws.region.static=${AWS_DEFAULT_REGION:us-east-1}
cloud.aws.stack.auto=false
cloud.aws.credentials.access-key=${AWS_ACCESS_KEY_ID}
cloud.aws.credentials.secret-key=${AWS_SECRET_ACCESS_KEY}

# Nome da sua fila (Criada na Fase 2)
queue.order-events=T04N_GABRIEL_EDUARDO_PHILIPPSEN_WANDSCHEER.fifo
