cloud.aws.region.static=${AWS_DEFAULT_REGION:us-east-1}
cloud.aws.stack.auto=false
cloud.aws.credentials.access-key=${AWS_ACCESS_KEY_ID}
cloud.aws.credentials.secret-key=${AWS_SECRET_ACCESS_KEY}

aws.sqs.queue.saida-estoque=SQS-SAIDA-ESTOQUE.fifo
aws.sqs.queue.entrada-estoque=SQS-ENTRADA-ESTOQUE.fifo
queue.order-events=T04N_GABRIEL_EDUARDO_PHILIPPSEN_WANDSCHEER.fifo